[tool.black]
line-length = 88

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.pytest]
addopts = "-v --asyncio"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_mode = "auto"

